name: Build and push images

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - "frontend/**"
      - "infra/Dockerfile.backend"
      - "infra/Dockerfile.frontend"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - "frontend/**"
      - "infra/Dockerfile.backend"
      - "infra/Dockerfile.frontend"

permissions:
  contents: read
  packages: write

jobs:

  build-backend:
    if: ${{ contains(github.event.head_commit.message, '[skip backend]') == false }}
    runs-on: ubuntu-latest
    name: Build Backend Image
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Vars
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "IMAGE=ghcr.io/epalorleant/futsal-backend" >> $GITHUB_OUTPUT

      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/Dockerfile.backend
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:sha-${{ steps.vars.outputs.SHORT_SHA }}
            ${{ steps.vars.outputs.IMAGE }}:latest


  build-frontend:
    if: ${{ contains(github.event.head_commit.message, '[skip frontend]') == false }}
    runs-on: ubuntu-latest
    name: Build Frontend Image
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Vars
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "IMAGE=ghcr.io/epalorleant/futsal-frontend" >> $GITHUB_OUTPUT

      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/Dockerfile.frontend
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:sha-${{ steps.vars.outputs.SHORT_SHA }}
            ${{ steps.vars.outputs.IMAGE }}:latest
